version: "3.2"
services:
   caddy:
      image: caddy
      container_name: caddy
      ports:
         - "80:80"
         - "443:443"
      volumes:
         - ./caddy:/etc/caddy
      command:
         - caddy
         - run
         - --config
         - /etc/caddy/Caddyfile
      logging:
         driver: "json-file"
         options:
            max-size: "9m"
            max-file: "3"
      
   v2ray:
      image: teddysun/v2ray:5.16.1
      container_name: v2ray
      ports:
         - "6789:6789"
      volumes:
         - ./v2ray:/etc/v2ray
      command:
         - v2ray
         - run
         - -config=/etc/v2ray/config.json
      logging:
         driver: "json-file"
         options:
            max-size: "9m"
            max-file: "3"
