bindPort = 7000
auth.method = "token"
auth.token = "12345678"

webServer.addr = "0.0.0.0"
webServer.port = 7500
webServer.user = "admin"
webServer.password = "admin123456"


vhostHTTPPort = 80
vhostHTTPSPort = 443